import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { AIModelStats } from '@shared/schema';
import { Brain, Trophy, MapPin, BarChart3 } from 'lucide-react';

interface StatisticsSummaryProps {
  totalItineraries: number;
  modelStats: AIModelStats[];
  isLoading?: boolean;
}

export default function StatisticsSummary({ totalItineraries, modelStats, isLoading = false }: StatisticsSummaryProps) {
  // Calculate which model is winning
  const winningModel = modelStats.length > 0 
    ? modelStats.reduce((prev, current) => 
        (prev.totalSelections > current.totalSelections) ? prev : current)
    : null;
  
  // Calculate the more accurate model
  const moreAccurateModel = modelStats.length > 0 
    ? modelStats.reduce((prev, current) => 
        (prev.percentageCorrect > current.percentageCorrect) ? prev : current)
    : null;

  if (isLoading) {
    return (
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {[1, 2, 3, 4].map((i) => (
          <Card key={i} className="animate-pulse">
            <CardHeader className="pb-2">
              <div className="h-4 w-24 bg-gray-200 rounded"></div>
            </CardHeader>
            <CardContent>
              <div className="h-8 w-16 bg-gray-200 rounded mb-2"></div>
              <div className="h-4 w-32 bg-gray-200 rounded"></div>
            </CardContent>
          </Card>
        ))}
      </div>
    );
  }

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="flex items-center text-base font-medium">
            <BarChart3 className="mr-2 h-4 w-4 text-primary" />
            Total Itineraries
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-3xl font-bold">{totalItineraries}</div>
          <p className="text-xs text-muted-foreground">
            Itineraries generated by our users
          </p>
        </CardContent>
      </Card>
      
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="flex items-center text-base font-medium">
            <Trophy className="mr-2 h-4 w-4 text-primary" />
            User Favorite
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold">{winningModel?.modelName || 'N/A'}</div>
          <p className="text-xs text-muted-foreground">
            {winningModel 
              ? `Chosen ${winningModel.totalSelections} times by users`
              : 'No data available yet'}
          </p>
        </CardContent>
      </Card>
      
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="flex items-center text-base font-medium">
            <Brain className="mr-2 h-4 w-4 text-primary" />
            Most Convincing
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold">{moreAccurateModel?.modelName || 'N/A'}</div>
          <p className="text-xs text-muted-foreground">
            {moreAccurateModel 
              ? `${moreAccurateModel.percentageCorrect}% correct guesses`
              : 'No data available yet'}
          </p>
        </CardContent>
      </Card>
      
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="flex items-center text-base font-medium">
            <MapPin className="mr-2 h-4 w-4 text-primary" />
            Success Rate
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold">
            {modelStats.length > 0 
              ? `${Math.round(modelStats.reduce((sum, stat) => sum + stat.correctGuesses, 0) / 
                  modelStats.reduce((sum, stat) => sum + stat.totalSelections, 0) * 100)}%`
              : 'N/A'}
          </div>
          <p className="text-xs text-muted-foreground">
            Overall correct AI model identification
          </p>
        </CardContent>
      </Card>
    </div>
  );
}